[assembly: System.Reflection.AssemblyVersion("0.1.4.2")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("0.1.4.2")] // Generated by build
[assembly: CitationClient.AssemblyPublishUrl("https://secureinstall.us/production/TownCenter/TownCenter.application")] // Generated by build
[assembly: System.Reflection.AssemblyProduct("TownCenter Client")] // Generated by build
