[assembly: System.Reflection.AssemblyVersion("1.0.5.1")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("1.0.5.1")] // Generated by build
[assembly: CitationClient.AssemblyPublishUrl("https://secureinstall.us/staging/TownCenter/TownCenter.application")] // Generated by build
