[assembly: System.Reflection.AssemblyVersion("1.0.5.0")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("1.0.5.0")] // Generated by build
[assembly: CitationClient.AssemblyPublishUrl("http://sameer-hpc/citation/AllSearch52.application")] // Generated by build
