[assembly: System.Reflection.AssemblyVersion("1.0.5.0")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("1.0.5.0")] // Generated by build
[assembly: CitationInstaller.AssemblyPublishUrl("http://sameer-hpc/citation/AllSearch52.application")] // Generated by build
[assembly: System.Reflection.AssemblyTitle("AllSearch52")] // Generated by build
[assembly: System.Reflection.AssemblyProduct("AllSearch52")] // Generated by build
