[assembly: System.Reflection.AssemblyVersion("1.0.5.1")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("1.0.5.1")] // Generated by build
[assembly: CitationInstaller.AssemblyPublishUrl("https://secureinstall.us/staging/TownCenter/TownCenter.application")] // Generated by build
[assembly: System.Reflection.AssemblyTitle("TownCenter")] // Generated by build
[assembly: System.Reflection.AssemblyProduct("TownCenter")] // Generated by build
