[assembly: System.Reflection.AssemblyVersion("0.1.3.6")] // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("0.1.3.6")] // Generated by build
[assembly: CitationInstaller.AssemblyPublishUrl("https://secureinstall.us/production/TownCenter/TownCenter.application")] // Generated by build
[assembly: System.Reflection.AssemblyTitle("TownCenter")] // Generated by build
[assembly: System.Reflection.AssemblyProduct("TownCenter")] // Generated by build
